name: GlobalSQA CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 11 using Adoptium (previously AdoptOpenJDK)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Install Chrome
      - name: Install Chrome
        run: sudo apt-get update && sudo apt-get install -y google-chrome-stable

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run tests
      - name: Run tests
        run: mvn verify

      # Upload Serenity Reports using pinned SHA for stability
      - name: Upload Serenity Reports
        uses: actions/upload-artifact@d5f4f7e8650eeef915c10c5c8f51b2c4cf941fba
        with:
          name: serenity-report
          path: target/site/serenity
