name: GlobalSQA CI Headed Workflow

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Xvfb (Virtual Display)
        run: |
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          Xvfb :99 -ac -screen 0 1920x1080x24 > /dev/null 2>&1 &

      - name: Run Serenity Tests in Headed Mode
        env:
          DISPLAY: :99
        run: |
          mvn clean verify -Dheadless.mode=false

      - name: Upload Serenity Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: target/site/serenity/
