name: GlobalSQA CI Workflow

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          #distribution: 'temurin'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Xvfb
        run: |
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          Xvfb :99 -ac -screen 0 1920x1080x24 > /dev/null 2>&1 &

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests in headed mode
        env:
          DISPLAY: :99
        run: |
          mvn clean verify "-Dcucumber.filter.tags=@smoke or @unitTest" -Dheadless.mode=false
