name: GlobalSQA CI Workflow

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 11 using Temurin (Adoptium)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Install Google Chrome
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run tests (Serenity should be configured for headless in serenity.conf or test setup)
      - name: Run tests
        run: mvn clean verify

      # Upload Serenity reports (optional)
#      - name: Upload Serenity Reports
#        if: always()  # Change to `failure()` if you only want on failure
#        uses: actions/upload-artifact@v4
#        with:
#          name: serenity-report
#          path: target/site/serenity
